# Pre-commit hooks for code quality
# Install with: pre-commit install
# Run manually: pre-commit run --all-files

repos:
  # Black code formatter
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args: [--line-length=99]
        language_version: python3.11

  # Ruff linter (fast Python linter)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        additional_dependencies: 
          - types-PyYAML
          - types-tqdm
          - numpy
          - jax
        exclude: ^tests/

  # General file fixes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]

  # YAML formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^examples/  # Don't format example YAML files

  # Docstring formatting
  - repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]

# Configuration for specific tools
files: ^pygsquig/
exclude: ^(docs/|htmlcov/|\.git/|\.pytest_cache/)

# Set default language version
default_language_version:
  python: python3.11