# Example configuration for Docker runs
# This demonstrates a typical turbulence simulation setup

grid:
  N: 256                    # Grid resolution (256x256)
  L: 6.283185307179586     # Domain size (2Ï€)

solver:
  alpha: 1.0               # Fractional Laplacian exponent (SQG)
  dissipation:
    type: hyperviscosity
    nu_p: 1.0e-6           # Hyperviscosity coefficient
    p: 8                   # Hyperviscosity order
  time_integration:
    method: RK4            # 4th-order Runge-Kutta
    dt: 0.001             # Time step

forcing:
  type: ring              # Ring forcing in Fourier space
  kf: 30.0               # Forcing wavenumber  
  dk: 2.0                # Forcing bandwidth
  epsilon: 0.1           # Energy injection rate
  tau_f: 0.0             # White noise forcing
  
simulation:
  t_end: 50.0            # Final time
  output_interval: 1.0    # Save every 1.0 time units
  checkpoint_interval: 10.0
  log_interval: 0.1

output:
  fields: ['theta']       # Fields to save
  diagnostics: ['energy_spectrum', 'scalar_flux']
  compress: true

initial_condition:
  type: random           # Random initial field
  amplitude: 0.01        # Initial amplitude
  seed: 42              # Random seed for reproducibility